name: Linting

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

concurrency:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run linting
        run: |
          flake8 .

  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install isort==5.12.0

      - name: Run linting
        run: |
          isort --check-only .

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mypy==1.4.1

      - name: Run mypy checks
        run: |
          mypy --install-types --non-interactive --namespace-packages -p camel
          mypy --install-types --non-interactive --namespace-packages -p test
          mypy --install-types --non-interactive --namespace-packages -p apps
